version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'VERY_STRONG_PASSWORD'
      POSTGRES_USER: 'shiva'
      POSTGRES_DB: 'shiva'
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256 --auth-local=scram-sha-256'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  shiva-bot:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    image: uristri/shiva-bot:dev
    container_name: shiva-bot
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data: